### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor u'Placeholder:0', which has shape '(?, 64, 64, 3)'

### ISSUE THREAD

**Issue by SniperZhao** [YadiraF/GAN#7]
When I try to run dcgan.py it returns me such error info:
Traceback (most recent call last):
  File "dcgan.py", line 108, in <module>
    dcgan.train(sample_dir)
  File "dcgan.py", line 58, in train
    feed_dict={self.X: X_b, self.z: sample_z(batch_size, self.z_dim)}
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor u'Placeholder:0', which has shape '(?, 64, 64, 3)'

Any suggestion?
My environment is: centos 7, tensorflow 1.4, cuda 8.0, cudnn 6.0.

**Comment by yfeng95** [comment]
Sorry for the late reply. (I have been so busy recently)
It seems something wrong with your input. Notice that, I didn't upload training images, you need prepare the training data yourself. 

Hope that helps.
